project:
  type: book
  output-dir: docs

book:
  title: "Remote Sensing Learning Diary"
  author: "Rahmadita Listianingrum"
  date: "1/26/2023"
  chapters:
    - index.qmd
    - week1.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

