# Assessment

# Assessment1 {.unnumbered}
-   Group presentation 
    -   A 10-minute group presentation "bidding" as contractors for a tender to solve an issue from policy. 
    -   Groups will select a single city and detail how Earth observation data could be applied to or improve their local, national or metropolitan development plans in achieving global development goals (e.g. New Urban Agenda, Sustainable Development Goals or the Sendai Framework for disaster risk reduction). 
    -   The city has a total of £500,000 to spend.
    -   The presentation will require **no analysis** to be undertaken but must be done in markdown

**Group code**

> all students in each group are active group members, respect each other, make appropriate and valid contributions, provide timely responses to their group and do not place unnecessary pressure or expectations on each other (e.g. working unsociable hours).

## Marking scheme {.unnumbered}

### 1. Problem definition {.unnumbered}
The research problem is globally or highly pertinent or topical to a social, environmental, political or other context and has been framed at the optimal spatial scale. There is extensive background research evaluating multiple forms of credible sources to produce a compelling and coherent framing of the research question, presented in a concise and informative manner.

### 2. Approach {.unnumbered}
Selected data and presented analytical methodology are able to perfectly solve the presented research question or the limitations are evidently understood and expertly expressed. The analysis is entirely appropriate to the problem. It demonstrates creativity, a comprehensive understanding of appropriate sophisticated techniques, exemplary technical proficiency and skills which are indicative of significant additional independent learning.

### 3. Project plan, risks and value for money {.unnumbered}
The project presents an exemplary plan. It is robust, logical, appropriate, and well informed, containing no ambiguity. It is evident how the deliverables will be useful to the city and could be incorporated into business as usual operations, this may include future areas of work or city challenges. All likely risks to the project have been identified and appropriate mitigative actions devised. Value for money in all aspects of the project is achieved, whilst producing tangible and actionable outputs.

# Assessment2 {.unnumbered}
-   Weekly learning diary using Quarto:
    -   **summarise, analyse and comment on** the material presented each we
    -   not a formal piece of writing 
    -   no specific formatting requirement (e.g. written response or flowcharts)
        -   Summary: summary of the content
        -   Applications: data / concepts / methods (or related concepts) have been applied in literature / policy or other studies
        -   Reflection: personal reflection on the presented content 

You should not just restate what has been presented in the lectures

-   What have you learnt
-   How has it been used or applied in literature
-   What are your thoughts on this

> all students should be familar with R, RStudio, Git and GitHub.

## Marking scheme {.unnumbered}

### 1. Content summary {.unnumbered}
A well-defined summary / introduction that expertly demonstrates clear, unambiguous and extensive comprehension of the data, methods and tools/policies*, their benefits, limitations and possible future developments.

*policies where appropriate

### 2. Applications of the content {.unnumbered}
Discussed applications of the taught content are systematic, extensive and evaluate several credible sources using an in- depth and thorough narrative. It seamlessly guides the reader through both how and why the methods / data/ tools have been applied whilst providing exemplary critical reflection on the approaches with reference to future literature advancements.

### 3. Personal reflection {.unnumbered}
An in depth and extensive personal reflection that demonstrates why the content may (or may not) be interesting, and presents an inquisitive dialogue to a wider application of the content. The skills, content, data and tools and placed within the broader discipline and it is evident how they could be used in future or may (or may not) lead to other avenues of analysis / work that could involve different datasets.

# Miscellanous {.unnumbered}

Mermaid mindmap (error live demo version)

```{mermaid}
mindmap
  root((Remote Sensing))
    Sensors
      Type of<br/>Sensors
        UAV and Drones
        Airplane and Helicopters
        Satellites
      Type of<br/>Orbits
        Geostationary
        Sun Synchronous
        Polar
      Type of<br>Resolutions
        Spatial resolution
        Spectral resolution
        Temporal resolution
        Radiometric
    Type of<br/>Remote Sensing
      Active Sensor
      Passive Sensor
    Electromagnetic<br/>Spectrum
      Spectral bands
        Multispectral
        Hyperspectral
    Image<br/>Classification
      Supervised Clasiffication
      Unsupervised Classification
      Object based Image Analysis
    Applications and Uses
      Agriculture
      Climate Change
      Disasters
      Environment
      Urban
```
